// biome-ignore lint/nursery/noExcessiveLinesPerFile: Shared mobile screen styles stay together until the mobile screens are split.
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 20,
  },
  actionRowCompact: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  bookAccent: {
    borderRadius: 8,
    height: 16,
    width: 16,
  },
  bookRow: {
    alignItems: 'center',
    backgroundColor: '#fbf4ea',
    borderColor: '#eadfce',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
  },
  bookTitle: {
    color: '#2c241f',
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
  },
  card: {
    backgroundColor: '#fffaf1',
    borderColor: '#eadfce',
    borderRadius: 28,
    borderWidth: 1,
    padding: 22,
    shadowColor: '#3d2f22',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 28,
  },
  cardBody: {
    color: '#6f655b',
    fontSize: 16,
    lineHeight: 24,
  },
  cardLabel: {
    color: '#9d7448',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.4,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  cardTitle: {
    color: '#2c241f',
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.4,
    marginBottom: 8,
  },
  cloudSummaryCard: {
    backgroundColor: '#efe2d1',
    borderColor: '#e0cfb8',
    borderRadius: 22,
    borderWidth: 1,
    padding: 16,
  },
  cloudSummaryText: {
    color: '#3b312a',
    fontSize: 16,
    fontWeight: '800',
  },
  chapterCard: {
    backgroundColor: '#fbf4ea',
    borderColor: '#eadfce',
    borderRadius: 20,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  chapterHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  chapterTitle: {
    color: '#6f4f31',
    flex: 1,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  content: {
    gap: 24,
    padding: 24,
    paddingBottom: 40,
  },
  documentRow: {
    alignItems: 'center',
    backgroundColor: '#fffaf1',
    borderRadius: 14,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  documentTitle: {
    color: '#3b312a',
    fontSize: 15,
    fontWeight: '600',
  },
  bodyInput: {
    color: '#4d433b',
    fontSize: 17,
    lineHeight: 27,
    minHeight: 360,
    paddingHorizontal: 0,
    paddingTop: 20,
    textAlignVertical: 'top',
  },
  authInput: {
    backgroundColor: '#fbf4ea',
    borderColor: '#eadfce',
    borderRadius: 16,
    borderWidth: 1,
    color: '#2c241f',
    fontSize: 16,
    marginTop: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  editorCard: {
    backgroundColor: '#fffaf1',
    borderColor: '#eadfce',
    borderRadius: 28,
    borderWidth: 1,
    padding: 22,
  },
  editorMetaText: {
    color: '#9b8d80',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 14,
  },
  editorShell: {
    flex: 1,
  },
  editorTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  drawerContent: {
    gap: 8,
    padding: 18,
    paddingBottom: 36,
    paddingTop: 64,
  },
  drawerEmptyText: {
    color: '#8d7d70',
    fontSize: 14,
    lineHeight: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  drawerEyebrow: {
    color: '#9d7448',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  drawerHeader: {
    gap: 6,
    marginBottom: 12,
  },
  drawerItem: {
    backgroundColor: '#fffaf1',
    borderColor: '#eadfce',
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  drawerItemText: {
    color: '#2c241f',
    fontSize: 16,
    fontWeight: '800',
  },
  drawerMeta: {
    color: '#7c7167',
    fontSize: 13,
    fontWeight: '700',
  },
  drawerSectionTitle: {
    color: '#9d7448',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.2,
    marginTop: 14,
    paddingHorizontal: 4,
    textTransform: 'uppercase',
  },
  drawerTitle: {
    color: '#241d19',
    fontSize: 28,
    fontWeight: '900',
    letterSpacing: -0.6,
  },
  emptyText: {
    color: '#7c7167',
    fontSize: 15,
    lineHeight: 22,
  },
  errorText: {
    color: '#a6534b',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 12,
  },
  eyebrow: {
    color: '#9d7448',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.6,
    textTransform: 'uppercase',
  },
  header: {
    gap: 10,
    paddingTop: 12,
  },
  inlineButton: {
    backgroundColor: '#efe2d1',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  inlineButtonText: {
    color: '#6f4f31',
    fontSize: 12,
    fontWeight: '800',
  },
  monoText: {
    color: '#6f655b',
    fontFamily: 'Courier',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 12,
  },
  menuButton: {
    alignItems: 'center',
    backgroundColor: '#2c241f',
    borderRadius: 999,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  menuButtonText: {
    color: '#fffaf1',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 24,
  },
  menuBackdrop: {
    backgroundColor: 'rgba(44, 36, 31, 0.24)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  menuOverlay: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 100,
  },
  menuPanel: {
    backgroundColor: '#f6efe5',
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: 320,
  },
  primaryButton: {
    backgroundColor: '#2c241f',
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  primaryButtonText: {
    color: '#fffaf1',
    fontSize: 15,
    fontWeight: '800',
  },
  pressedRow: {
    opacity: 0.62,
    transform: [{ scale: 0.99 }],
  },
  rowChevron: {
    color: '#b49a7a',
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 24,
  },
  safeArea: {
    backgroundColor: '#f6efe5',
    flex: 1,
  },
  secondaryButton: {
    backgroundColor: '#efe2d1',
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  secondaryButtonText: {
    color: '#3b312a',
    fontSize: 15,
    fontWeight: '800',
  },
  section: {
    gap: 10,
  },
  sectionTitle: {
    color: '#2c241f',
    fontSize: 18,
    fontWeight: '800',
  },
  selectedBookRow: {
    alignItems: 'center',
    backgroundColor: '#efe2d1',
    borderColor: '#d8c2a8',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
  },
  stack: {
    gap: 24,
  },
  statusDot: {
    backgroundColor: '#7d9a65',
    borderRadius: 5,
    height: 10,
    width: 10,
  },
  statusDotError: {
    backgroundColor: '#a6534b',
    borderRadius: 5,
    height: 10,
    width: 10,
  },
  statusPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#efe2d1',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  statusText: {
    color: '#5e5046',
    fontSize: 13,
    fontWeight: '700',
  },
  subtitle: {
    color: '#6f655b',
    fontSize: 17,
    lineHeight: 26,
  },
  title: {
    color: '#241d19',
    fontSize: 44,
    fontWeight: '800',
    letterSpacing: -1.2,
  },
  titleInput: {
    color: '#2c241f',
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.6,
    lineHeight: 36,
    marginBottom: 4,
    minHeight: 46,
    paddingBottom: 2,
    paddingTop: 4,
  },
});
